"""Wiki → Markdown 导出。

把一份 WikiDocument 序列化成单个 .md 文件：
- 按 index.tree 的顺序递归遍历，拼接所有页面正文
- 文内 `#wiki:<id>` → 加粗纯文本（去掉链接）
- 文内 `#code:ref_N` → ``` `path:L起-L止` ``` 行内 code（基于 metadata.code_refs）
- category 节点作为一级分组标题，无正文
"""

from __future__ import annotations

import re
from io import StringIO

from backend.models.wiki_models import PageMetadata, WikiDocument, WikiPage

_CODE_LINK_RE = re.compile(r"\[([^\]]+)\]\(#code:([A-Za-z0-9_]+)\)")
_HEADING_RE = re.compile(r"^(#{1,6})\s", re.MULTILINE)


def export_to_markdown(doc: WikiDocument) -> str:
    """产出单份 Markdown 字符串。"""
    buf = StringIO()
    id_to_page = {p.id: p for p in doc.pages}

    # 页首元信息
    buf.write(f"<!-- Generated by CoReader at {doc.generated_at} -->\n\n")

    # 从 index.root 递归遍历。顶层 overview 作 H1，其下 category 也作 H1，
    # chapter/module/topic 作 H2。category 无 content_md，只打标题。
    _visit(
        page_id=doc.index.root,
        level=1,
        doc=doc,
        id_to_page=id_to_page,
        buf=buf,
        visited=set(),
    )

    return buf.getvalue().rstrip() + "\n"


def _visit(
    *,
    page_id: str,
    level: int,
    doc: WikiDocument,
    id_to_page: dict[str, WikiPage],
    buf: StringIO,
    visited: set[str],
) -> None:
    if page_id in visited:
        return
    visited.add(page_id)

    node = doc.index.tree.get(page_id)
    page = id_to_page.get(page_id)
    if node is None or page is None:
        return

    # 标题：category/overview 用当前 level；子页用 level+1
    title_prefix = "#" * min(max(level, 1), 6)
    buf.write(f"{title_prefix} {page.title}\n\n")

    # category 节点没有正文，跳过 content 渲染
    if page.type != "category" and page.content_md:
        body = _transform_links(page.content_md, page.metadata)
        body = _rebase_headings(body, level)
        buf.write(body.rstrip() + "\n\n")

    for child_id in node.children:
        _visit(
            page_id=child_id,
            level=level + 1,
            doc=doc,
            id_to_page=id_to_page,
            buf=buf,
            visited=visited,
        )


def _rebase_headings(content: str, page_level: int) -> str:
    """把 content_md 中的标题级别重新定基到 page_level。

    exporter 已经为页面写了 page_level 级标题，content 里的子标题应从
    page_level+1 开始。如果 content 首行就是最高级标题（页面自身标题），
    先去掉它，再根据剩余标题的最小级别计算偏移。
    """
    lines = content.split("\n")

    # 找首行标题级别
    first_heading = _HEADING_RE.match(lines[0]) if lines else None
    if first_heading:
        first_h = len(first_heading.group(1))
        # 去掉首标题（与页面 title 重复）及其后空行
        lines = lines[1:]
        while lines and not lines[0].strip():
            lines = lines[1:]

    # 找剩余内容中最小标题级别
    min_h = 7
    for line in lines:
        m = _HEADING_RE.match(line)
        if m:
            min_h = min(min_h, len(m.group(1)))
    if min_h > 6:
        return "\n".join(lines)

    delta = (page_level + 1) - min_h
    if delta == 0:
        return "\n".join(lines)

    def shift(m: re.Match[str]) -> str:
        new_level = min(max(len(m.group(1)) + delta, 1), 6)
        return "#" * new_level + " "

    return "\n".join(_HEADING_RE.sub(shift, line) for line in lines)


def _transform_links(content_md: str, metadata: PageMetadata) -> str:
    """把 #wiki:<id> 和 #code:<ref> 转成离线可读的形式。"""

    # #wiki:<id> → 去掉链接，只保留文字
    out = re.sub(r"\[([^\]]+)\]\(#wiki:[A-Za-z0-9_]+\)", r"**\1**", content_md)

    # [text](#code:ref_N) → [text]（附 `path:Lstart-Lend`）
    # 拿不到 ref 就保留原文
    def _code_sub(match: re.Match[str]) -> str:
        text = match.group(1)
        ref_id = match.group(2)
        ref = metadata.code_refs.get(ref_id)
        if not ref:
            return match.group(0)
        loc = f"{ref.file}:L{ref.start_line}-L{ref.end_line}"
        return f"**{text}**（`{loc}`）"

    out = _CODE_LINK_RE.sub(_code_sub, out)
    return out
